---
abstract: 'Talk to a Gitlab installation via its API.'
author:
  - 'Alan Young <harleypig@gmail.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Scalar::Util: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.94'
  Test::Most: '0'
  Test::NoWarnings: '0'
  Test::UseAllModules: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Gitlab
no_index:
  directory:
    - t
    - xt
requires:
  Carp: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Params::Validate::Checks: '0'
  Regexp::Common: '0'
  Regexp::Common::Email::Address: '0'
  namespace::autoclean: '0'
  strict: '0'
  warnings: '0'
resources: {}
version: '0.04'
